package models

// Models etc. which are not autogenerated

var (
	ValidPeriods = map[string]bool{
		"month": true,
		"week": true,
	}
)

type ErrorMessage struct {
	Message string `json:"message"`
}
